version: '3.9'

services:
  books-client:
    container_name: google_books_search
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      NODE_ENV: production